export type IIconName =
    | 'telegram'
    | 'whatsApp'
    | 'linkedIn'
    | 'vk'
    | 'behance'
    | 'moon'
    | 'sun'
    | 'star'
    | 'logo'
    | 'phone'
    | 'mail'
    | 'triangle-rounded'
    | 'upload-file'
