import {FC, PropsWithChildren} from "react";
import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import Providers from "@/app/_providers";
import "./globals.css";
import {HeaderLayout} from "@/widgets/layout";
import {Container} from "@/shared/ui/wrappers";

const inter = Open_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<Readonly<PropsWithChildren>> = ({children}) => (
    <html lang="en">
        <body className={inter.className}>
            <Providers>
                {children}
            </Providers>
        </body>
    </html>
);

export default RootLayout
